// Conteúdo PT/EN para a landing da Musicake
// Estrutura por seção -> bloco

const COPY = {
  pt: {
    nav: { listen: "para ouvintes", artists: "para artistas", waitlist: "entrar na lista" },
    heroHooks: [
      { kicker: "musicake", title: ["Música boa", "merece ser", "compartilhada "], sub: "Musicake ajuda artistas e ouvintes a compartilhar músicas de forma mais simples, universal e significativa." },
      { kicker: "musicake", title: ["A música", "merece uma", "experiência melhor."], sub: "Uma camada bonita e útil entre artistas, ouvintes e plataformas. Sem fricção, sem login, sem prender ninguém em lugar nenhum." },
      { kicker: "manifesto", title: ["Um link.", "Todas as", "plataformas."], sub: "Compartilhe uma música uma vez. Quem recebe abre onde quiser — Spotify, Apple, Deezer, YouTube. A música no centro, a plataforma no canto." },
      { kicker: "para artistas", title: ["Lance sua", "música como", "um evento."], sub: "Esqueça o pré-save burocrático. Crie uma página de lançamento com release, bastidores e contato direto com quem importa: seus fãs." },
    ],
    ctaPrimary: "entrar na lista de espera",
    ctaSecondary: "ver como funciona",
    productsKicker: "duas formas de cuidar da música",
    productsIntro: "Musicake começa com duas soluções que conversam entre si — uma para o momento em que a música circula, outra para o momento em que ela nasce.",
    baking: {
      name: "Baking",
      tag: "para artistas",
      headline: "O lançamento que seus fãs merecem.",
      desc: "Uma alternativa humana ao pré-save. Crie uma página de lançamento com release, mensagem, bastidores e colete e-mail ou WhatsApp de quem quer ouvir no dia.",
      bullets: ["release com contexto e bastidores", "coleta de e-mail e WhatsApp", "notificação no dia do lançamento", "página personalizada do artista"],
    },
    slice: {
      name: "Slice",
      tag: "para todo mundo",
      headline: "Compartilhe uma música. Em qualquer plataforma.",
      desc: "Aponte o botão de compartilhar de qualquer player. A Musicake cria automaticamente um link que abre a música na plataforma de quem recebe.",
      bullets: ["funciona em Spotify, Apple, Deezer, YouTube…", "um único link, todas as plataformas", "sem login, sem fricção", "preview no próprio link"],
    },
    audienceKicker: "",
    audienceTitle: ["Feito para quem", "ama música", "de verdade."],
    audiences: [
      { name: "Os melhores ouvintes", desc: "Aqueles que mandam música pros amigos sem se importar com a plataforma de cada um." },
      { name: "Artistas independentes", desc: "Que querem lançar com menos fricção e mais conexão direta com o público." },
      { name: "Curadores e criadores", desc: "Que constroem playlists, posts e recomendações que precisam viver fora da bolha de uma plataforma." },
      { name: "Blogs, selos e comunidades", desc: "Que querem páginas musicais mais ricas, bonitas e úteis pra sua audiência." },
    ],
    howSliceKicker: "como funciona — Slice",
    howSliceTitle: "Como compartilhar uma música em 3 passos",
    howSlice: [
      { n: 1, label: "Aponte o botão de compartilhar em qualquer plataforma", phone: "share-source" },
      { n: 2, label: "Selecione o app Musicake na lista do seu dispositivo", phone: "share-sheet" },
      { n: 3, label: "Musicake cria automaticamente um link com acesso à música em todas as plataformas", phone: "slice-link" },
    ],
    howSliceDesktop: [
      { n: 1, label: "Instale a extensão Musicake no seu navegador. Funciona com Chrome, Arc, Edge e Firefox.", browser: "install" },
      { n: 2, label: "Ouça música em qualquer plataforma. O ícone da Musicake aparece direto na interface.", browser: "listening" },
      { n: 3, label: "Clique no ícone e a Musicake gera um link universal pronto pra enviar.", browser: "link-ready" },
    ],
    howSliceTabs: { mobile: "📱 no celular", desktop: "💻 no navegador" },
    howSliceTabHints: { mobile: "compartilhe direto do app que você já usa", desktop: "um clique no ícone da Musicake e pronto" },
    howBakingKicker: "como funciona — Baking",
    howBakingTitle: "Como lançar uma música em 4 movimentos.",
    howBaking: [
      { n: 1, label: "Crie a sua página de lançamento.\n\nSeu 'Plate' no Musicake." },
      { n: 2, label: "Envie pra todo mundo. Quem recebe só precisa deixar e-mail ou WhatsApp. Sem login, sem chatice." },
      { n: 3, label: "Seus fãs recebem uma notificação no dia do lançamento com um link para seu Plate." },
      { n: 4, label: "Seu Plate personalizado contém links para audição, release e área de interação para os fãs." },
    ],
    manifestoBlock: { kicker: "nossa crença", title: ["A música", "merece", "mais."], body: "Música é experiência, significado e conexão.\nNão deveria ser tratada como conteúdo.\nMusicake existe pra devolver cuidado e intenção à forma como as músicas circulam." },
    finalKicker: "entre primeiro",
    finalTitle: ["Vamos compartilhar", "música de", "um jeito novo."],
    finalSub: "Estamos em fase de testes com as primeiras pessoas — ouvintes, artistas, curadores e selos. Deixe seu e-mail e te avisamos quando for sua vez.",
    finalCta: "quero entrar",
    finalSecondary: "sou artista, quero falar com vocês",
    faqKicker: "perguntas que ouvimos sempre",
    faq: [
      { q: "Preciso pagar pra usar?", a: "O Slice será gratuito pra ouvintes. Pra artistas, teremos um plano gratuito generoso e um plano pago com mais recursos de lançamento." },
      { q: "Funciona com qualquer plataforma?", a: "Sim — Spotify, Apple Music, Deezer, YouTube Music, Tidal e outras principais. Vamos crescendo a lista." },
      { q: "Como vocês ganham dinheiro?", a: "Com planos pra artistas e selos. Nunca vendendo dado de ouvinte, nunca prendendo música atrás de paywall." },
      { q: "Quando lança?", a: "Estamos em beta fechado em 2026. Entrando na lista, você é avisado primeiro." },
    ],
    testimonialsKicker: "primeiras vozes",
    testimonials: [
      { quote: "Finalmente consigo mandar uma música pro meu pai sem perguntar 'você usa qual?'", author: "Marina · ouvinte beta" },
      { quote: "É a primeira ferramenta de lançamento que parece pensada pelo artista, não pela plataforma.", author: "Léo Brandt · produtor" },
      { quote: "Meu blog precisa disso. Linkar uma música é sempre um pesadelo.", author: "Coletivo Pulso · curadoria" },
    ],
    footer: "Musicake · uma camada gostosa entre artistas, ouvintes e plataformas · 2026",
  },
  en: {
    nav: { listen: "for listeners", artists: "for artists", waitlist: "join the list" },
    heroHooks: [
      { kicker: "musicake", title: ["Good music", "deserves to", "be shared."], sub: "Musicake helps artists and listeners share, release and receive music in a simpler, more universal and more meaningful way." },
      { kicker: "musicake", title: ["Music", "deserves a", "better experience."], sub: "A beautiful, useful layer between artists, listeners and platforms. No friction, no login, no one trapped anywhere." },
      { kicker: "manifesto", title: ["One link.", "Every", "platform."], sub: "Share a song once. The person who gets it opens it wherever they want — Spotify, Apple, Deezer, YouTube. Music in the center, platform in the corner." },
      { kicker: "for artists", title: ["Release your", "music like", "an event."], sub: "Forget the bureaucratic pre-save. Build a release page with notes, behind-the-scenes and a direct line to the people who matter: your fans." },
    ],
    ctaPrimary: "join the waitlist",
    ctaSecondary: "see how it works",
    productsKicker: "two ways to take care of music",
    productsIntro: "Musicake starts with two products that talk to each other — one for the moment music circulates, one for the moment it is born.",
    baking: {
      name: "Baking",
      tag: "for artists",
      headline: "The release your fans deserve.",
      desc: "A human alternative to the pre-save. Build a release page with notes, message and behind-the-scenes, and collect email or WhatsApp from people who want to listen on launch day.",
      bullets: ["release with context & BTS", "collect email and WhatsApp", "drop-day notification", "your own artist page"],
    },
    slice: {
      name: "Slice",
      tag: "for everyone",
      headline: "Share a song. On any platform.",
      desc: "Tap the share button on any player. Musicake automatically builds a link that opens the song on whatever platform the receiver uses.",
      bullets: ["works on Spotify, Apple, Deezer, YouTube…", "one link, every platform", "no login, no friction", "preview inside the link"],
    },
    audienceKicker: "",
    audienceTitle: ["Built for people", "who actually", "love music."],
    audiences: [
      { name: "The real listeners", desc: "The ones who text songs to friends and don't care which app they use." },
      { name: "Independent artists", desc: "Who want to release with less friction and a more direct connection to their audience." },
      { name: "Curators & creators", desc: "Who build playlists, posts and recommendations that need to live outside one platform's bubble." },
      { name: "Blogs, labels & communities", desc: "That want richer, prettier, more useful music pages for their audience." },
    ],
    howSliceKicker: "how it works — Slice",
    howSliceTitle: "How to share a song in 3 steps.",
    howSlice: [
      { n: 1, label: "Tap the share button on any platform", phone: "share-source" },
      { n: 2, label: "Pick Musicake from your device's share sheet", phone: "share-sheet" },
      { n: 3, label: "Musicake builds a link that opens on every platform", phone: "slice-link" },
    ],
    howSliceDesktop: [
      { n: 1, label: "Install the Musicake extension in your browser. Works on Chrome, Arc, Edge and Firefox.", browser: "install" },
      { n: 2, label: "Play music on any platform. The Musicake icon shows up right inside the interface.", browser: "listening" },
      { n: 3, label: "Click the icon and Musicake builds a universal link ready to share.", browser: "link-ready" },
    ],
    howSliceTabs: { mobile: "📱 on mobile", desktop: "💻 in the browser" },
    howSliceTabHints: { mobile: "share straight from the app you already use", desktop: "one click on the Musicake icon and you're done" },
    howBakingKicker: "how it works — Baking",
    howBakingTitle: "How to release in 4 moves.",
    howBaking: [
      { n: 1, label: "Build your release page (your 'plate') on Musicake." },
      { n: 2, label: "Send it to everyone. People only need to drop email or WhatsApp." },
      { n: 3, label: "Your fans get a notification on launch day with a link to your plate." },
      { n: 4, label: "Your custom plate has the song, the notes and a space to interact with fans." },
    ],
    manifestoBlock: { kicker: "what we believe", title: ["Music", "deserves", "better."], body: "Music is experience, context, discovery, bond and presence. It shouldn't be treated like a link or content. Musicake exists to give care and intent back to how music travels." },
    finalKicker: "get in first",
    finalTitle: ["Let's release", "music in a", "new way."],
    finalSub: "We're opening the first seats — listeners, artists, curators and labels. Drop your email and we'll tell you when it's your turn.",
    finalCta: "I want in",
    finalSecondary: "I'm an artist, let's talk",
    faqKicker: "questions we get a lot",
    faq: [
      { q: "Do I have to pay?", a: "Slice will be free for listeners. For artists, there's a generous free tier and a paid plan with extra release features." },
      { q: "Does it work with any platform?", a: "Yes — Spotify, Apple Music, Deezer, YouTube Music, Tidal and others. We keep adding more." },
      { q: "How do you make money?", a: "Plans for artists and labels. Never selling listener data, never trapping music behind a paywall." },
      { q: "When does it launch?", a: "Closed beta in 2026. Join the list and we'll let you know first." },
    ],
    testimonialsKicker: "first voices",
    testimonials: [
      { quote: "I can finally send a song to my dad without asking 'which app do you use?'", author: "Marina · beta listener" },
      { quote: "The first release tool that feels designed by an artist, not by a platform.", author: "Léo Brandt · producer" },
      { quote: "My blog needs this. Linking a song is always a nightmare.", author: "Pulso collective · curation" },
    ],
    footer: "Musicake · a delicious layer between artists, listeners and platforms · 2026",
  },
};

window.COPY = COPY;
